### ISSUE TITLE
The list of rules displayed in SWRLTab and SQWRLTab does not synchronize with the ontology

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#25] opened 2016-03-09 01:21 UTC
There are different ways that this can be experienced. For example:
1. Deleting a rule in SWRLTab does not make the rule disappear in SQWRLTab, and vice versa (this may not be an issue if #20 is resolved)
2. Reloading an ontology (File -> Reload OR pressing Ctrl+Shift+R) would not show the new list of rules, as it is in the reloaded file.
3. Changing the name of a rule may cause the rule disappear from the list (this may be a separate issue on its own),
4. Changing the name of a rule may update the information in the table, but the rule engine will still refer to the old name, which it won't be able to find any more, and would complain about it.

**Comment by martinjoconnor** [comment] 2016-06-04 17:32
Fixed by updated to OWLAPI 4.2.3.

**Closed by martinjoconnor** 2016-06-04 17:32 UTC

**Comment by Liu131452** [comment] 2022-07-28 03:43
Sorry, I mean that the atomic order of the specific content in each SWRL rule is disordered, which makes it impossible to use SWRLTab and Sqwrltab for inference, which will trigger inference errors caused by variable order.Looking forward to your guidance.
